language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"

# command to install dependencies
install:
    - pip install numpy scipy matplotlib
# command to run tests
script:
  - pytest unit4/my_test/circle_main.py

